export const FETCH_BEERS =  'FETCH_BEERS';
export const FETCH_BEERS_ERROR = 'FETCH_BEERS_ERROR';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';

export const BEERS_PAGE_LAST = 'FETCH_BEERS_PAGE_LAST';
export const BEERS_PAGE_NEXT = 'FETCH_BEERS_PAGE_NEXT';
export const BEERS_PER_PAGE = 'FETCH_BEERS_PER_PAGE';
export const BEERS_PAGE_SEARCH = 'FETCH_BEERS_SEARCH';
export const BEERS_FIRST_LETTER = 'BEERS_FIRST_LETTER';
export const BEERS_FILTER = 'BEERS_FILTER';
export const BEERS_FILTER_NULL = 'BEERS_FILTER_NULL';